const mongoose = require('mongoose');

const FileSchema = new mongoose.Schema({
    // --- 1. BASIC FILE INFO ---
    owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, // The person who clicked upload
    workspaceId: { type: String, default: null },
    fileName: { type: String, required: true },
    s3Key: { type: String, required: true }, // The Original Encrypted File
    fileSize: { type: Number, required: true },
    s3Url: { type: String }, // Your AWS S3 URL
    fileHash: { type: String }, // For Blockchain integrity
    date: { type: Date, default: Date.now },

    // --- 2. SHARING FEATURES (Keep these) ---
    shareToken: { type: String, default: null }, // Unique link token
    shareExpires: { type: Date, default: null }, // Expiration date for link

    // --- 3. NEW: COMPLIANCE & PII FEATURES ---
    // The Redacted File (Encrypted), generated by your Python Worker
    redactedS3Key: { type: String, default: null },

    // Status Tracker for the Frontend Dashboard
    complianceStatus: {
        type: String,
        enum: ['pending', 'scanning', 'clean', 'redacted', 'failed', 'skipped', 'rejected'],
        default: 'pending'
    },

    riskScore: { type: Number, default: 100 },
    classification: {
        type: String,
        enum: ['PUBLIC', 'SENSITIVE', 'INTERNAL', 'RESTRICTED', 'UNKNOWN'],
        default: 'UNKNOWN'
    },
    riskKeywords: [String], // To store "CONFIDENTIAL", "NDA"
    rejectionReason: { type: String, default: '' }, // To show user why it was deleted

    // The JSON report from GLiNER (e.g., found "John Doe" on page 1)
    piiReport: [
        {
            text: String,
            type: { type: String }, // e.g. "NRIC NUMBER"
            page: Number,
            score: Number
        }
    ],
});

module.exports = mongoose.model('file', FileSchema);