// models/File.js
const mongoose = require('mongoose');

const FileSchema = new mongoose.Schema({
    // --- 1. BASIC FILE INFO ---
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    fileName: { type: String, required: true },
    s3Key: { type: String, required: true }, // The Original Encrypted File
    fileSize: { type: Number, required: true },
    fileHash: { type: String }, // For Blockchain integrity
    uploadDate: { type: Date, default: Date.now },

    // --- 2. SHARING FEATURES (Keep these) ---
    shareToken: { type: String, default: null }, // Unique link token
    shareExpires: { type: Date, default: null }, // Expiration date for link

    // --- 3. NEW: COMPLIANCE & PII FEATURES ---
    // The Redacted File (Encrypted), generated by your Python Worker
    redactedS3Key: { type: String, default: null },

    // Status Tracker for the Frontend Dashboard
    complianceStatus: {
        type: String,
        enum: ['pending', 'scanning', 'clean', 'redacted', 'failed', 'skipped'],
        default: 'pending'
    },

    // The JSON report from GLiNER (e.g., found "John Doe" on page 1)
    piiReport: { type: Object, default: {} }
});

module.exports = mongoose.model('File', FileSchema);